name: genomica_tp1
channels:
  - bioconda
  - conda-forge
dependencies:
  - python
  - fastqc      # QC
  - spades      # Montagem Illumina
  - flye        # Montagem Nanopore
  - unicycler   # Montagem Híbrida
  - quast       # Avaliação
  - busco       # Avaliação
  - prokka      # Anotação
  - samtools
  - pandas      # Ciar sumario.tsv
  - shellcheck  # Validar scripts bash
  - wget        # Para garantir reprodutibilidade total (incluir máquinas onde o wget não vem instalado por defeito)
  - sra-tools   # Converter ficheiros para FASTQ
